export const CLOCK_SIZE = 500;
export const CLOCK_RADIUS = CLOCK_SIZE / 2;
export const CLOCK_HAND_HOUR_LENGTH = CLOCK_RADIUS * 0.5;
export const CLOCK_HAND_HOUR_WIDTH = 20;
export const CLOCK_HAND_MINUTE_LENGTH = CLOCK_RADIUS * 0.8;
export const CLOCK_HAND_MINUTE_WIDTH = 10;